# Generated by Django 3.2.8 on 2022-12-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(blank=True, max_length=4)),
                ('passport_number', models.CharField(blank=True, max_length=6)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('policy', models.CharField(blank=True, max_length=16)),
                ('insurance_number', models.CharField(blank=True, max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]